---
# defaults file for openvpn

openvpn_network_addr: "10.9.0.0"
openvpn_network_mask: 255.255.255.0
openvpn_networks: []
openvpn_push_dns: []
openvpn_domains:  []
openvpn_port: 4300
openvpn_proto: udp6
openvpn_use_updown_scripts: false
