---
- name: Create gatus app directories
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    mode: "0755"
  loop:
    - "/var/data/containers/gatus/config"
    - "/var/data/containers/gatus/data"
  loop_control:
    loop_var: dir

- name: Render gatus config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../stacks/gatus/config.yaml.j2"
    dest: "/var/data/containers/gatus/config/config.yaml"
    mode: "0644"
  notify: "Restart gatus"
