# Set the interface on which dnsmasq operates.
# If not set, all the interfaces is used.
interface=eth0
bind-dynamic
interface=lo
# only bind to configured interfaces. (Defaults to all even if explicitely set above)
# bind-interfaces

# To disable dnsmasq's DNS server functionality.
port=53

# *****************************************************
#              DNS functionality
# *****************************************************

# Never forward plain names (without a dot or domain part)
domain-needed
# Never forward addresses in the non-routed address spaces.
bogus-priv

# If you don't want dnsmasq to read /etc/resolv.conf or any other
# file, getting its servers from this file instead (see below), then
# uncomment this.
no-resolv

cache-size=10000

# Upstream DNS servers
server=8.8.8.8
server=1.1.1.1
#server=/eu.ad.cuda-inc.com/10.27.1.60
#server=/ngdev.eu.ad.cuda-inc.com/10.27.1.60

# Fake domain to test the configuration
address=/testdomain.tld/1.2.3.4

# Force the upstream servers to be used _in_ order
strict-order

# Add custom domain to hosts in my network
local=/home/bpatsch-it.net/
domain=home
expand-hosts

# --address (and --server) work with IPv6 addresses too.
#address=/www.thekelleys.org.uk/fe80::20d:60ff:fe36:f83

# Add the IPs of all queries to yahoo.com, google.com, and their
# subdomains to the vpn and search ipsets:
#ipset=/yahoo.com/google.com/vpn,search

# *****************************************************
#              DHCP functionality
# *****************************************************

# To enable dnsmasq's DHCP server functionality.
dhcp-range=192.168.8.50,192.168.8.99,255.255.255.0,12h

# Set static IPs for selected devices
dhcp-host=90:2b:d2:f7:04:2d,router,192.168.8.1,24h				            # Router
dhcp-host=14:10:9f:e9:d8:1a,macbook,set:specialhosts,192.168.8.10,24h		# macbook
dhcp-host=44:00:49:64:6e:56,firetv-old,set:firetv,192.168.8.11,24h			# firetv
dhcp-host=10:09:f9:24:1f:09,firetv,set:firetv,192.168.8.12,24h			    # firetv
#dhcp-host=2c:76:8a:79:28:a0,drucker,set:specialhosts,192.168.8.239,24h		# HP Printer
dhcp-host=ac:50:de:d8:cb:b4,drucker,set:specialhosts,192.168.8.239,24h		# Brother printer

# Set gateway as Router. Following two lines are identical.
dhcp-option=3,192.168.8.1
dhcp-option-force=tag:firetv,3,192.168.8.242
dhcp-option-force=tag:specialhosts,3,192.168.8.242

# Set DNS server
dhcp-option=6,192.168.8.242
dhcp-option-force=tag:specialhosts,6,192.168.8.242

# Logging.
log-facility=/var/log/dnsmasq.log   # logfile path.
log-async
log-dhcp    # log dhcp related messages.
# log-queries # log queries.

# If you want dnsmasq to detect attempts by Verisign to send queries
# to unregistered .com and .net hosts to its sitefinder service and
# have dnsmasq instead return the correct NXDOMAIN response, uncomment
# this line. You can add similar lines to do the same for other
# registries which have implemented wildcard A records.
bogus-nxdomain=64.94.110.11


# If a DHCP client claims that its name is "wpad", ignore that.
# This fixes a security hole. see CERT Vulnerability VU#598349
dhcp-name-match=set:wpad-ignore,wpad
dhcp-ignore-names=tag:wpad-ignore
