---
alerting:
  teams-workflows:
    webhook-url: "{{ vault_gatus_teams_webhook_url }}"
    client:
      insecure: false
    default-alert:
      description: "healthcheck failed"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

  ntfy:
    topic: "{{ vault_gatus_ntfy_infra_topic }}"
    default-alert:
      description: "healthcheck failed"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

gatus_endpoint_groups:
  - name: prod-responsive
    interval: 5m
    url_scheme: https
    response_time: 3500
    alerts:
      - type: teams-workflows
    hosts:
      - booking.casablanca.at
      - bookingengine.casablanca.at
      - changelog.casablanca.at
      - cloud.casablanca.at
      - docs.casablanca.at
      - frontend.casablanca.at
      - guestapp.casablanca.at
      - ibe.casablanca.at
      - install.casablanca.at
      - interface.casablanca.at
      - it-support.casablanca.at
      - my.casablanca.at
      - online.casablanca.at
      - research.casablanca.at
      - s1.casablanca.at
      - status.casablanca.at
      - www.casablanca.at

  - name: prod-slow
    interval: 5m
    url_scheme: https
    response_time: 5000
    hosts:
      - connectivity.casablanca.at
      - go.casablanca.at
      - academy.casablanca.at
      - intern.academy.casablanca.at
      - partner.academy.casablanca.at
      - rookie.academy.casablanca.at

  - name: infra
    interval: 5m
    url_scheme: icmp
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: teams-workflows
      - type: ntfy
    hosts:
      - pip-campus.casablanca.at
      - pip-ibk.casablanca.at
