---
all:
  children:
    docker_hosts:
      hosts:
        saturn:
        p-docker01:
        bp-testdeployment:
    plain_hosts:
      hosts:
        fileserver:
        hetzner01:
    prod:
      hosts:
        saturn:
        p-docker01:
        fileserver:
        bp-testdeployment:
        hetzner01:
