---
ansible_user: ansible
ansible_port: 2222
ansible_become: true

# stacks:
#   - paperless-ngx
#   - gatus

# paperless_ngx:
#   domain: paperless.example.com
#   admin_email: ops@example.com
#   admin_password: "{{ vault_paperless_admin_password }}"

# gatus:
#   domain: status.example.com
